import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";

const bricolageSans = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage-sans",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolageSans.variable} from-blue-400 via-indigo-100/80 to-purple-100/20  antialiased`}
        style={{ fontFamily: "var(--font-bricolage-sans)" }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
